In [3]:
print("Experiment tracking")

Experiment tracking

In [5]:
import sys
from pathlib import Path
import os

PROJECT_ROOT = Path().resolve().parents[1]
print(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))

/Users/kavinkumarbaskar/project/machine_learning/mlops_basics

In [10]:
from feature_store.feature_store import FeastFeatureStore

feast = FeastFeatureStore(path=os.path.join(PROJECT_ROOT, "feature_store//feature_repo"))
print(feast.store)

FeatureStore(
    repo_path=PosixPath('/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/feature_store/feature_repo'),
    config=RepoConfig(project='housing_feature_store', project_description=None, provider='local', registry_config={'registry_type': 'sql', 'path': 'postgresql+psycopg://postgres:password@localhost:5432/feast_registry', 'cache_ttl_seconds': 60, 'sqlalchemy_config_kwargs': {'echo': False, 'pool_pre_ping': True}}, online_config={'type': 'postgres', 'host': 'localhost', 'port': 5432, 'database': 'feast_online', 'db_schema': 'public', 'user': 'postgres', 'password': 'password'}, auth={'type': 'no_auth'}, offline_config={'type': 'postgres', 'host': 'localhost', 'port': 5432, 'database': 'feast_offline', 'db_schema': 'public', 'user': 'postgres', 'password': 'password'}, batch_engine_config='local', feature_server=None, flags=None, repo_path=PosixPath('/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/feature_store/feature_repo'), entity_key_serialization_version=3, coerce_tz_aware=True, materialization_config=MaterializationConfig(pull_latest_features=False)),
    registry=<feast.infra.registry.sql.SqlRegistry object at 0x11e5382f0>,
    provider=<feast.infra.passthrough_provider.PassthroughProvider object at 0x11e67dfd0>
)

In [11]:
entity_df = feast.get_entity_dataframe(path=os.path.join(str(PROJECT_ROOT) + "/feature_store/data/house_target.parquet"))
entity_df

     house_id     price               event_timestamp
0           1  13300000 2025-12-17 14:24:03.120401000
1           2  12250000 2025-12-17 14:24:03.120398750
2           3  12250000 2025-12-17 14:24:03.120396500
3           4  12215000 2025-12-17 14:24:03.120394250
4           5  11410000 2025-12-17 14:24:03.120392000
..        ...       ...                           ...
540       541   1820000 2025-12-17 14:24:03.119186000
541       542   1767150 2025-12-17 14:24:03.119183750
542       543   1750000 2025-12-17 14:24:03.119181500
543       544   1750000 2025-12-17 14:24:03.119179250
544       545   1750000 2025-12-17 14:24:03.119177000

[545 rows x 3 columns]

In [12]:
from datetime import datetime, timedelta
from feature_store.exec_feature_store import ExecuteFeatureStore
fs = feast.store
efs= ExecuteFeatureStore()

In [13]:
online_df = (
    ExecuteFeatureStore().get_online_features(
        fstore=fs,
        entity_df=entity_df[["house_id"]],
    )
    .to_df()
)

online_df

Fetching online features...

     house_id  mainroad  bedrooms      area
0           1         1  1.403419  1.046726
1           2         1  1.403419  1.757010
2           3         1  0.047278  2.218232
3           4         1  1.403419  1.083624
4           5         1  1.403419  1.046726
..        ...       ...       ...       ...
540       541         1 -1.308863 -0.991879
541       542         0  0.047278 -1.268613
542       543         1 -1.308863 -0.705921
543       544         0  0.047278 -1.033389
544       545         1  0.047278 -0.599839

[545 rows x 4 columns]

In [15]:
# Separating the features and labels
target = entity_df['price']
online_features = online_df.drop(labels=["house_id"], axis=1)
online_features

     mainroad  bedrooms      area
0           1  1.403419  1.046726
1           1  1.403419  1.757010
2           1  0.047278  2.218232
3           1  1.403419  1.083624
4           1  1.403419  1.046726
..        ...       ...       ...
540         1 -1.308863 -0.991879
541         0  0.047278 -1.268613
542         1 -1.308863 -0.705921
543         0  0.047278 -1.033389
544         1  0.047278 -0.599839

[545 rows x 3 columns]

In [81]:
import importlib
import model.house_model

importlib.reload(model.house_model)

In [82]:
from model.house_model import HousePriceModel

model = HousePriceModel()
# print(model)
model.train_model(online_features, target)

Model trained and saved as model.pkl

In [83]:
model.configure_mlflow()

MLflow Tracking URI: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow
exp_id: 0
MLflow Experiment: House_Price_Prediction

<Experiment: artifact_location='mlflow-artifacts:/d60cfe03c7e54afc868190a79dcb49ad', creation_time=1765981640717, experiment_id='0', last_update_time=1765981640717, lifecycle_stage='active', name='House_Price_Prediction', tags={}>

In [84]:
model_info = model.register()

2025/12/17 19:57:26 INFO mlflow.system_metrics.system_metrics_monitor: Skip logging GPU metrics. Set logger level to DEBUG for more details.
2025/12/17 19:57:26 INFO mlflow.system_metrics.system_metrics_monitor: Started monitoring system metrics.
/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/.venv/lib/python3.13/site-packages/mlflow/models/model.py:365: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.utc_time_created = str(utc_time_created or datetime.utcnow())
2025/12/17 19:57:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Logged run with params: {'fit_intercept': True, 'positive': True}, mean_cv_score: -2201507329935.4316, std_test_score: 397269400084.4091
🏃 View run child_run_0 at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0/runs/9256066945d8427486927fde97487387
🧪 View experiment at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0

/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/.venv/lib/python3.13/site-packages/mlflow/models/model.py:365: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.utc_time_created = str(utc_time_created or datetime.utcnow())
2025/12/17 19:57:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Logged run with params: {'fit_intercept': True, 'positive': False}, mean_cv_score: -2201507329935.4312, std_test_score: 397269400084.4087
🏃 View run child_run_1 at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0/runs/c5e259e7e6694bb199b022e89ced84dd
🧪 View experiment at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0

/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/.venv/lib/python3.13/site-packages/mlflow/models/model.py:365: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.utc_time_created = str(utc_time_created or datetime.utcnow())
2025/12/17 19:57:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Logged run with params: {'fit_intercept': False, 'positive': True}, mean_cv_score: -4536519879926.2070, std_test_score: 934351777743.8822
🏃 View run child_run_2 at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0/runs/f1454e65f465450a9abebcdd6635e8e6
🧪 View experiment at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0

/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/.venv/lib/python3.13/site-packages/mlflow/models/model.py:365: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.utc_time_created = str(utc_time_created or datetime.utcnow())
2025/12/17 19:58:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Logged run with params: {'fit_intercept': False, 'positive': False}, mean_cv_score: -4536519879926.2070, std_test_score: 934351777743.8812
🏃 View run child_run_3 at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0/runs/91493b5910de46e18adf90899467d859
🧪 View experiment at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0

/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
Successfully registered model 'house_price_prediction'.
2025/12/17 19:58:37 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: house_price_prediction, version 1
Created version '1' of model 'house_price_prediction'.

🏃 View run LinearReg_GridSearch_Best at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0/runs/f1362361afc54a25a4f99a105f5a89aa
🧪 View experiment at: https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0

2025/12/17 19:58:40 INFO mlflow.system_metrics.system_metrics_monitor: Stopping system metrics monitoring...
2025/12/17 19:58:41 INFO mlflow.system_metrics.system_metrics_monitor: Successfully terminated system metrics monitoring!

In [85]:
# https://dagshub.com/kavinkumarbaskar/house_price_mlops.mlflow/#/experiments/0/runs/f1362361afc54a25a4f99a105f5a89aa
model_info.model_uri

'runs:/f1362361afc54a25a4f99a105f5a89aa/house_model'