In [1]:
print("Feast Feature Store")

Feast Feature Store

In [9]:
import pandas as pd

df = pd.read_csv("../../data/Housing_processed.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,1,0
1,12250000,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0,0
2,12250000,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1,1
3,12215000,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,1,0
4,11410000,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0,0

In [10]:
timestamps = pd.date_range(
    end=pd.Timestamp.now(),
    start=pd.Timestamp.now(),
    periods=len(df),
    freq=None
).to_frame(name="event_timestamp", index=False)

df['event_timestamp'] = timestamps['event_timestamp']
df['house_id'] = range(1, len(df) + 1)
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,event_timestamp,house_id
0,13300000,1.046726,1.403419,1.421812,1.378217,1,0,0,0,1,1.517692,1,0,2025-12-17 14:24:03.120401000,1
1,12250000,1.757010,1.403419,5.405809,2.532024,1,0,0,0,1,2.679409,0,0,2025-12-17 14:24:03.120398750,2
2,12250000,2.218232,0.047278,1.421812,0.224410,1,0,1,0,0,1.517692,1,1,2025-12-17 14:24:03.120396500,3
3,12215000,1.083624,1.403419,1.421812,0.224410,1,0,1,0,1,2.679409,1,0,2025-12-17 14:24:03.120394250,4
4,11410000,1.046726,1.403419,-0.570187,0.224410,1,1,1,0,1,1.517692,0,0,2025-12-17 14:24:03.120392000,5

In [11]:
# Splitting the dataset into features (X) and target (y)
X = df.drop(columns=['price'])
y = pd.DataFrame(df[['house_id', 'price', 'event_timestamp']])

print("X features:")
print(X.head())

print("y target:")
print(y.head())

X features:
       area  bedrooms  bathrooms   stories  mainroad  guestroom  basement  \
0  1.046726  1.403419   1.421812  1.378217         1          0         0
1  1.757010  1.403419   5.405809  2.532024         1          0         0
2  2.218232  0.047278   1.421812  0.224410         1          0         1
3  1.083624  1.403419   1.421812  0.224410         1          0         1
4  1.046726  1.403419  -0.570187  0.224410         1          1         1

   hotwaterheating  airconditioning   parking  prefarea  furnishingstatus  \
0                0                1  1.517692         1                 0
1                0                1  2.679409         0                 0
2                0                0  1.517692         1                 1
3                0                1  2.679409         1                 0
4                0                1  1.517692         0                 0

                event_timestamp  house_id
0 2025-12-17 14:24:03.120401000         1
1 2025-12-17 14:24:03.120398750         2
2 2025-12-17 14:24:03.120396500         3
3 2025-12-17 14:24:03.120394250         4
4 2025-12-17 14:24:03.120392000         5
y target:
   house_id     price               event_timestamp
0         1  13300000 2025-12-17 14:24:03.120401000
1         2  12250000 2025-12-17 14:24:03.120398750
2         3  12250000 2025-12-17 14:24:03.120396500
3         4  12215000 2025-12-17 14:24:03.120394250
4         5  11410000 2025-12-17 14:24:03.120392000

In [7]:
import sqlalchemy as db
from sqlalchemy import text
from dotenv import load_dotenv
import os

load_dotenv()  # Load environment variables from .env file

connstr = os.getenv("POSTGRE_SQL_CONN_STR")
offline_db = os.getenv("POSTGRE_SQL_OFFLINE_DB")
full_connstr = f"{connstr}/{offline_db}"

engine = db.create_engine(full_connstr)


with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database(), current_user"))
    print(result.fetchone())

('feast_offline', 'postgres')

In [12]:
X.to_sql('house_features_sql', engine, if_exists='replace', index=False)
y.to_sql('house_target_sql', engine, if_exists='replace', index=False)

-1

In [19]:
parent_dir = os.path.abspath(os.path.join(os.getcwd(), "..", "data"))
X.to_parquet(path=os.path.join(parent_dir, 'house_features.parquet'), index=False)
y.to_parquet(path=os.path.join(parent_dir, 'house_target.parquet'), index=False)

In [1]:
import sys
from pathlib import Path
import os

PROJECT_ROOT = Path().resolve().parents[1]
print(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))

/Users/kavinkumarbaskar/project/machine_learning/mlops_basics

In [2]:
from feature_store.feature_store import FeastFeatureStore
feast = FeastFeatureStore(path=os.path.join(str(PROJECT_ROOT) + "/feature_store/feature_repo"))
print(feast.store)

/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/.venv/lib/python3.13/site-packages/feast/permissions/auth_model.py:35: PydanticDeprecatedSince212: Using `@model_validator` with mode='after' on a classmethod is deprecated. Instead, use an instance method. See the documentation at https://docs.pydantic.dev/2.12/concepts/validators/#model-after-validator. Deprecated in Pydantic V2.12 to be removed in V3.0.
  @model_validator(mode="after")

FeatureStore(
    repo_path=PosixPath('/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/feature_store/feature_repo'),
    config=RepoConfig(project='housing_feature_store', project_description=None, provider='local', registry_config={'registry_type': 'sql', 'path': 'postgresql+psycopg://postgres:password@localhost:5432/feast_registry', 'cache_ttl_seconds': 60, 'sqlalchemy_config_kwargs': {'echo': False, 'pool_pre_ping': True}}, online_config={'type': 'postgres', 'host': 'localhost', 'port': 5432, 'database': 'feast_online', 'db_schema': 'public', 'user': 'postgres', 'password': 'password'}, auth={'type': 'no_auth'}, offline_config={'type': 'postgres', 'host': 'localhost', 'port': 5432, 'database': 'feast_offline', 'db_schema': 'public', 'user': 'postgres', 'password': 'password'}, batch_engine_config='local', feature_server=None, flags=None, repo_path=PosixPath('/Users/kavinkumarbaskar/project/machine_learning/mlops_basics/feature_store/feature_repo'), entity_key_serialization_version=3, coerce_tz_aware=True, materialization_config=MaterializationConfig(pull_latest_features=False)),
    registry=<feast.infra.registry.sql.SqlRegistry object at 0x11843eba0>,
    provider=<feast.infra.passthrough_provider.PassthroughProvider object at 0x1195d0980>
)

In [5]:
entity_df = feast.get_entity_dataframe(path=os.path.join(str(PROJECT_ROOT) + "/feature_store/data/house_target.parquet"))
entity_df

     house_id     price               event_timestamp
0           1  13300000 2025-12-17 14:24:03.120401000
1           2  12250000 2025-12-17 14:24:03.120398750
2           3  12250000 2025-12-17 14:24:03.120396500
3           4  12215000 2025-12-17 14:24:03.120394250
4           5  11410000 2025-12-17 14:24:03.120392000
..        ...       ...                           ...
540       541   1820000 2025-12-17 14:24:03.119186000
541       542   1767150 2025-12-17 14:24:03.119183750
542       543   1750000 2025-12-17 14:24:03.119181500
543       544   1750000 2025-12-17 14:24:03.119179250
544       545   1750000 2025-12-17 14:24:03.119177000

[545 rows x 3 columns]

In [6]:
features=[
        "house_features:area",
        "house_features:bedrooms",
        "house_features:mainroad"
    ]
hist_df = feast.get_historical_features(entity_df, features)
hist_df

,house_id,price,event_timestamp,area,bedrooms,mainroad
0,1,13300000,2025-12-17 14:24:03.120401,1.046726,1.403419,1
1,2,12250000,2025-12-17 14:24:03.120398,1.757010,1.403419,1
2,3,12250000,2025-12-17 14:24:03.120396,2.218232,0.047278,1
3,4,12215000,2025-12-17 14:24:03.120394,1.083624,1.403419,1
4,5,11410000,2025-12-17 14:24:03.120392,1.046726,1.403419,1
...,...,...,...,...,...,...
540,541,1820000,2025-12-17 14:24:03.119186,-0.991879,-1.308863,1
541,542,1767150,2025-12-17 14:24:03.119183,-1.268613,0.047278,0
542,543,1750000,2025-12-17 14:24:03.119181,-0.705921,-1.308863,1
543,544,1750000,2025-12-17 14:24:03.119179,-1.033389,0.047278,0
544,545,1750000,2025-12-17 14:24:03.119177,-0.599839,0.047278,1

In [3]:
from datetime import datetime, timedelta
from feature_store.exec_feature_store import ExecuteFeatureStore
fs = feast.store
efs= ExecuteFeatureStore()
# efs.materialize(end_date=datetime.now(), start_date=datetime.now() - timedelta(days=10), fstore=fs)
# feast.materialize(datetime.now(), datetime.now() - timedelta(days=10))

In [7]:
# entity_rows = pd.DataFrame(entity_df["house_id"]).to_dict(orient="records")
# online_df = fs.get_online_features(entity_rows, features)
# online_df

# entity_rows = (
#     entity_df[["house_id"]]
#     .to_dict(orient="records")
# )

online_df = (
    ExecuteFeatureStore().get_online_features(
        fstore=fs,
        entity_df=entity_df[["house_id"]],
    )
    .to_df()
)

online_df

Fetching online features...

     house_id  mainroad  bedrooms      area
0           1         1  1.403419  1.046726
1           2         1  1.403419  1.757010
2           3         1  0.047278  2.218232
3           4         1  1.403419  1.083624
4           5         1  1.403419  1.046726
..        ...       ...       ...       ...
540       541         1 -1.308863 -0.991879
541       542         0  0.047278 -1.268613
542       543         1 -1.308863 -0.705921
543       544         0  0.047278 -1.033389
544       545         1  0.047278 -0.599839

[545 rows x 4 columns]

In [11]:
feast.materialize(end_date=datetime.now(), incremental=True)

Materializing 1 feature views to 2025-12-17 17:18:47+00:00 into the postgres online store.

house_features from 2025-12-17 17:01:48+00:00 to 2025-12-17 17:18:47+00:00: